# Generated by Django 5.1.5 on 2025-02-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='account_name',
            field=models.CharField(default=1, max_length=150, verbose_name='account_name'),
            preserve_default=False,
        ),
    ]
