# Generated by Django 5.1.5 on 2025-02-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='account_id'),
        ),
    ]
