# Generated by Django 5.1.5 on 2025-01-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('magic_type', models.CharField(choices=[('sorcerer', '真語魔法'), ('conjurer', '操霊魔法'), ('wizard', '深智魔法'), ('priest', '基本神聖魔法'), ('unique_priest', '特殊神聖魔法'), ('magitech', '魔動機術'), ('fairy_tamer', '基本妖精魔法'), ('spcial_fairy_tamer', '特殊妖精魔法'), ('druid', '森羅魔法'), ('daemon_ruler', '召異魔法'), ('abyssgazer', '奈落魔法')], max_length=20, verbose_name='魔法の系統')),
                ('rank', models.IntegerField(verbose_name='魔法ランク')),
                ('target', models.CharField(max_length=100, verbose_name='対象')),
                ('range_shape', models.CharField(max_length=100, verbose_name='射程/形状')),
                ('resistance', models.CharField(choices=[('hit', '必中'), ('optionally', '任意'), ('none', 'なし'), ('negate', '消滅'), ('reduce', '半減'), ('shorten', '短縮')], max_length=10, verbose_name='抵抗')),
                ('duration', models.CharField(max_length=50, verbose_name='時間')),
                ('cost', models.CharField(max_length=100, verbose_name='消費')),
                ('summary', models.TextField(verbose_name='概要')),
                ('attribute', models.CharField(blank=True, max_length=50, null=True, verbose_name='属性')),
                ('effect', models.TextField(verbose_name='効果')),
                ('extended_effect1', models.TextField(blank=True, null=True, verbose_name='拡張効果1')),
                ('extended_effect2', models.TextField(blank=True, null=True, verbose_name='拡張効果2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '魔法',
                'verbose_name_plural': '魔法一覧',
                'ordering': ['rank', 'name'],
            },
        ),
    ]
