# Generated by Django 5.1.5 on 2025-01-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic',
            name='magic_type',
            field=models.CharField(choices=[('sorcerer', '真語魔法'), ('conjurer', '操霊魔法'), ('wizard', '深智魔法'), ('priest', '基本神聖魔法'), ('unique_priest', '特殊神聖魔法'), ('magitech', '魔動機術'), ('fairy_tamer', '基本妖精魔法'), ('special_fairy_tamer', '特殊妖精魔法'), ('druid', '森羅魔法'), ('daemon_ruler', '召異魔法'), ('abyssgazer', '奈落魔法')], max_length=20, verbose_name='魔法の系統'),
        ),
    ]
