# Generated by Django 5.1.5 on 2025-01-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_magic_magic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='magic',
            name='spell',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='詠唱'),
        ),
    ]
