# Generated by Django 5.1.5 on 2025-01-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_magic_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic',
            name='spell',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='詠唱'),
        ),
    ]
