# Generated by Django 5.1.5 on 2025-02-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_magic_spell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic',
            name='effect',
            field=models.CharField(verbose_name='効果'),
        ),
    ]
